# The name of the workflow
name: First Workflow
# What triggers the workflow
on: workflow_dispatch
# A list of jobs
jobs: 
# This is the first named job.
  first-job:
  # What environment to use. See this link for more details and a list of supported runners:
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#overview-of-github-hosted-runners 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting 
        run: echo "hello world"
      - name: Print goodbye
        run: echo "goodbye!"
